const ACTION_TYPES = {
  API_PENDING: 'API_PENDING',
  API_SUCCESS: 'API_SUCCESS',
  API_ERROR: 'API_ERROR',
  SET_TOKEN: 'SET_TOKEN',
  SET_MOVIES: 'SET_MOVIES',
  DELETE_MOVIE: 'DELETE_MOVIE',
  DELETE_TOKEN: 'DELETE_TOKEN',
};
export default ACTION_TYPES;
